name: Sync templates from Verdas repository
permissions:
    contents: write
on:
   push:
     branches:
      - templates
   schedule:
      - cron: '0 0 * * 0' # every sunday at midnight
   workflow_dispatch: # Allows manual triggering of the workflow

jobs:
    get-templates:
        runs-on: ubuntu-latest
        steps:
           - name: Checkout repo
             uses: actions/checkout@v4
             with:
                fetch-depth: 0
                ref: templates
           - name: Clone external repository 
             run: | 
                rm -rf external-repo 
                git clone --depth 1 https://github.com/verda-cloud/model-templates.git external-repo

           - name: Update templates folder
             working-directory: gen-ai-playground
             run: |
                mkdir -p backend/templates
                cp -r ../external-repo/templates/* backend/templates/ || true

           - name: Configure git
             run: |
                git config user.name "github-actions"
                git config user.email "actions@github.com"

           - name: Commit changes if needed
             run: |
                git add backend/templates
                git diff --quiet --cached || git commit -m "Sync templates from Verdas repository [skip ci]"      
           - name: Push
             run: |
                git push
    
       
    
